---
- hosts: localhost
  #gather_facts: yes
  #become: true
  vars:
    users:
      - name: 'root'
        homedir: '/root'
      - name: 'user'
        homedir: '/home/user'
    git:
      #TODO: To hide sensitive data use ansible vault
      email: "sergey.pakhomov.89@gmail.com"
      name: "Sergey Pakhomov"
  roles:
    - git
    - vim
    - tmux
    - tilix
    - screen
