---
- hosts: localhost
  #gather_facts: yes
  #become: true
  vars:
    users:
      - name: 'root'
        homedir: '/root'
        ps1: "export PS1='\\[\\033[01;31m\\]#\\[\\033[00m\\] '" # red #
      - name: 'user'
        homedir: '/home/user'
        ps1: "export PS1='\\[\\033[01;32m\\]$\\[\\033[00m\\] '" # green $
    git:
      #TODO: To hide sensitive data use ansible vault
      email: "sergey.pakhomov.89@gmail.com"
      name: "Sergey Pakhomov"
  roles:
    - git
    - vim
    - tmux
    - tilix
    - screen
    - bash
